/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ApiDealRequestsRouteImport } from './routes/api/deal-requests'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiVerifyTransactionRouteImport } from './routes/api/verify-transaction'
import { Route as VerifyReferenceIdRouteImport } from './routes/verify/$referenceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealRequestsRoute = ApiDealRequestsRouteImport.update({
  id: '/api/deal-requests',
  path: '/api/deal-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyTransactionRoute = ApiVerifyTransactionRouteImport.update({
  id: '/api/verify-transaction',
  path: '/api/verify-transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReferenceIdRoute = VerifyReferenceIdRouteImport.update({
  id: '/$referenceId',
  path: '/$referenceId',
  getParentRoute: () => VerifyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/api/deal-requests': typeof ApiDealRequestsRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/verify/$referenceId': typeof VerifyReferenceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/api/deal-requests': typeof ApiDealRequestsRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/verify/$referenceId': typeof VerifyReferenceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/fees': typeof FeesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/safety': typeof SafetyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/api/deal-requests': typeof ApiDealRequestsRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/api/verify-transaction': typeof ApiVerifyTransactionRoute
  '/verify/$referenceId': typeof VerifyReferenceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/fees'
    | '/how-it-works'
    | '/privacy'
    | '/request'
    | '/reviews'
    | '/rules'
    | '/safety'
    | '/services'
    | '/terms'
    | '/verify'
    | '/api/deal-requests'
    | '/api/reviews'
    | '/api/verify-transaction'
    | '/verify/$referenceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/fees'
    | '/how-it-works'
    | '/privacy'
    | '/request'
    | '/reviews'
    | '/rules'
    | '/safety'
    | '/services'
    | '/terms'
    | '/verify'
    | '/api/deal-requests'
    | '/api/reviews'
    | '/api/verify-transaction'
    | '/verify/$referenceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/fees'
    | '/how-it-works'
    | '/privacy'
    | '/request'
    | '/reviews'
    | '/rules'
    | '/safety'
    | '/services'
    | '/terms'
    | '/verify'
    | '/api/deal-requests'
    | '/api/reviews'
    | '/api/verify-transaction'
    | '/verify/$referenceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  FeesRoute: typeof FeesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  ReviewsRoute: typeof ReviewsRoute
  RulesRoute: typeof RulesRoute
  SafetyRoute: typeof SafetyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRouteWithChildren
  ApiDealRequestsRoute: typeof ApiDealRequestsRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiVerifyTransactionRoute: typeof ApiVerifyTransactionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal-requests': {
      id: '/api/deal-requests'
      path: '/api/deal-requests'
      fullPath: '/api/deal-requests'
      preLoaderRoute: typeof ApiDealRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-transaction': {
      id: '/api/verify-transaction'
      path: '/api/verify-transaction'
      fullPath: '/api/verify-transaction'
      preLoaderRoute: typeof ApiVerifyTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$referenceId': {
      id: '/verify/$referenceId'
      path: '/$referenceId'
      fullPath: '/verify/$referenceId'
      preLoaderRoute: typeof VerifyReferenceIdRouteImport
      parentRoute: typeof VerifyRoute
    }
  }
}

interface VerifyRouteChildren {
  VerifyReferenceIdRoute: typeof VerifyReferenceIdRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyReferenceIdRoute: VerifyReferenceIdRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  FeesRoute: FeesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  ReviewsRoute: ReviewsRoute,
  RulesRoute: RulesRoute,
  SafetyRoute: SafetyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRouteWithChildren,
  ApiDealRequestsRoute: ApiDealRequestsRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiVerifyTransactionRoute: ApiVerifyTransactionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
